---
abstract: 'Write object oriented scripts with ease'
author:
  - 'Jan Henning Thorsen'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Applify
no_index:
  directory:
    - example
    - inc
    - t
requires:
  Cwd: 3.31
  File::Basename: 2.7
  Getopt::Long: 2.38
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Applify
  homepage: http://metacpan.org/dist/Applify
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jhthorsen/applify.git
version: 0.01
